import cadquery as cq

# --- Part 1: Cylinder ---
part_1_radius = 0.3024 * 0.6048  # Sketch radius scaled
part_1_height = 0.4839

part_1 = cq.Workplane("XY").circle(part_1_radius).extrude(part_1_height)

# --- Part 2: Cylinder ---
part_2_radius = 0.2117 * 0.4234  # Sketch radius scaled
part_2_height = 0.121

part_2 = cq.Workplane("XY").circle(part_2_radius).extrude(part_2_height)

# --- Part 3: Protruding Rod ---
part_3_radius = 0.0121 * 0.0242  # Sketch radius scaled
part_3_height = 0.0847

part_3 = cq.Workplane("XY").circle(part_3_radius).extrude(part_3_height)

# --- Coordinate System Transformation for Part 3 ---
part_3 = part_3.translate((0.5827, 0.0242, 0.0))

# --- Part 4: Cube with Cylinder ---
part_4_size = 0.0759 * 0.0754  # Sketch size scaled
part_4_height = 0.0605

part_4 = cq.Workplane("XY").box(part_4_size, part_4_size, part_4_height)

# --- Coordinate System Transformation for Part 4 ---
part_4 = part_4.translate((0.2642, 0.2743, 0.0))

# --- Assembly ---
assembly = part_1.union(part_2).union(part_3).union(part_4)

cq.exporters.export(assembly, "./stlcq/0048/00488818.stl")</s>

import cadquery as cq

# --- Parameters ---
sketch_scale = 0.6048
part_1_radius = 0.3024 * sketch_scale
part_2_radius = 0.2117 * sketch_scale
part_3_radius = 0.0121 * sketch_scale
part_4_size = 0.0759 * sketch_scale
part_4_height = 0.0605

# --- Part 1: Cylinder ---
part_1 = cq.Workplane("XY").circle(part_1_radius).extrude(0.4839)

# --- Part 2: Cylinder ---
part_2 = cq.Workplane("XY").circle(part_2_radius).extrude(0.121)

# --- Coordinate System Transformation for Part 2 ---
part_2 = part_2.translate((0.0, 0.0, 0.4839))

# --- Part 3: Protruding Rod ---
part_3 = cq.Workplane("XY").circle(part_3